### ISSUE TITLE
csrf_detected | CSRF detected

### ISSUE THREAD

**Issue by lanrion** [mikamai/discourse-doorkeeper-sso#2]
Hi, I come across an issue:

localhost:4000 is oauth2 proiver,  a new project, rails 4.1.4
Discorse run on the port: 3000, the master branch
- Exception:

``` ruby
OmniAuth::Strategies::OAuth2::CallbackError at /auth/doorkeeper/callback
csrf_detected | CSRF detected
```
- settings.yml

``` yml

# these are global settings
title: doorkeeper log in
message: Log in via doorkeeper (make sure your browser does not block popups)
frame_width: 920
frame_height: 800


# enviornment specific settings:
environments:
  development:
    endpoint: http://localhost:4000 
    key: 0b6865a300616a54c623acc6437a6a07a680f670f85188ea3949bc4885cc6dde
    secret: 206174ce78ecabb7a732bb1904876014a2d612150abde0e215cd7897d77813ef
```

When I click the "Authorize" button, it raise the exception:

``` ruby
OmniAuth::Strategies::OAuth2::CallbackError at /auth/doorkeeper/callback
csrf_detected | CSRF detected
```

Thanks.
